# Generated by Django 2.2.3 on 2019-07-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='report',
            field=models.TextField(blank=True, max_length=100000),
        ),
    ]
