# Generated by Django 2.2.3 on 2019-07-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0002_auto_20190728_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='report',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
